---
- name: Install OS dependencies
  apt:  pkg="{{ item }}"
        state=latest
        update_cache=yes
  with_items:
    - build-essential
    - git
    - lsb-release
    - python3
    - python3-dev
    - python3-pip
    - python3-virtualenv
  tags:
    - install
    - deps

- name: Add MongoDB apt key
  apt_key:  id=EA312927
            keyserver=hkp://keyserver.ubuntu.com
  tags:
    - install
    - mongodb
    - deps

- name: Add MongoDB repository
  apt_repository: repo='deb http://repo.mongodb.org/apt/debian wheezy/mongodb-org/3.2 main'
                  state=present
                  update_cache=yes
  tags:
    - install
    - mongodb
    - deps

- name: Install MongoDB
  apt:  pkg="{{ item }}"
        state=latest
  with_items:
    - mongodb-org
    - libsnappy1
  tags:
    - install
    - mongodb
    - deps
